"""edit games table

Revision ID: 94b309b0c025
Revises: ab6e09ff882b
Create Date: 2025-10-22 08:49:59.100350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b309b0c025'
down_revision: Union[str, Sequence[str], None] = 'ab6e09ff882b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'owner_id')
    # ### end Alembic commands ###
