"""edit games table #3

Revision ID: c9503e4ddbd2
Revises: e3e835277c07
Create Date: 2025-10-15 02:51:13.262779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9503e4ddbd2'
down_revision: Union[str, Sequence[str], None] = 'e3e835277c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('description', sa.String(), nullable=True))
    op.add_column('games', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'rating')
    op.drop_column('games', 'description')
    # ### end Alembic commands ###
