"""edit games table #2

Revision ID: e3e835277c07
Revises: 5af99594e745
Create Date: 2025-10-11 01:57:16.938182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e835277c07'
down_revision: Union[str, Sequence[str], None] = '5af99594e745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('games', 'list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('list', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('games', 'title')
    # ### end Alembic commands ###
