"""edit games table

Revision ID: 5af99594e745
Revises: 4fd76478b2df
Create Date: 2025-10-11 01:56:46.766646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af99594e745'
down_revision: Union[str, Sequence[str], None] = '4fd76478b2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('list', sa.String(), nullable=True))
    op.drop_column('games', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('games', 'list')
    # ### end Alembic commands ###
